### ISSUE TITLE
how to install in spacemacs?

### ISSUE THREAD

**Issue by yunhor** [AdamNiederer/vue-html-mode#1]
When I install vue-html-mode in spacemacs and reload spacemacs,it will be removed.Would you tell me how to use vue-html-mode in spacemacs? Thank you!

**Comment by AdamNiederer** [comment]
I've tested this with multiple packages in spacemacs; this appears to be an issue with spacemacs, rather than this package.

**Comment by richarddewit** [comment]
@yunhor add it to `dotspacemacs-additional-packages` in your `.spacemacs` file, like this:

```
   ;; List of additional packages that will be installed without being
   ;; wrapped in a layer. If you need some configuration for these
   ;; packages, then consider creating a layer. You can also put the
   ;; configuration in `dotspacemacs/user-config'.
   dotspacemacs-additional-packages '(some-other-package
                                      vue-html-mode)
```
