### ISSUE TITLE
JavaScript Highlighting

### ISSUE THREAD

**Issue by AnharMiah** [AdamNiederer/vue-html-mode#7]
I'm not sure if this is a genuine issue as I'm new to `emacs`, I may have configured it wrong, but there doesn't seem to be any `JavaScript` highlighting at all?

![image](https://user-images.githubusercontent.com/11503147/33672725-d833cfb8-daa2-11e7-83f4-a94f6b370dd2.png)

**Comment by AdamNiederer** [comment]
This mode is intended to be used in conjunction with vue-mode, and only handles html highlighting and indentation. Please install and activate `vue-mode` to get full template editing support - this mode will be automatically configured to handle just the HTML portion for you.

**Comment by AnharMiah** [comment]
hi @AdamNiederer thanks thats perfect!
